import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ServiceList from '../src/components/service/ServiceList'
import BarberList from '../src/components/barberList/BarberList'
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import '../node_modules/@mui/x-date-pickers/AdapterDayjs/index.js';
import "react-datepicker/dist/react-datepicker.css";
import MuiPicker from '../src/components/muiPicker/MuiPicker';
import ClientInformation from '../src/components/clientInformation/ClientInformation';

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Romantiko Barbershop</title>
        <meta name="description" content="Generated by create next app" />
        {/** Need to change ico - lenard */}
        <link rel="icon" href="/favicon.ico" /> 

      
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello World - Lenard
        </h1>

        <p className={styles.description}>
          This is the Home page -----------
        </p>

       
      </main>

      
    </div>
  )
}


